# Generated by Django 4.0.1 on 2022-10-08 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDOWorks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_of_work', models.CharField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('incomplete', models.BooleanField(default=False)),
            ],
        ),
    ]
